version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - area:infra
      - bloc-s
    open-pull-requests-limit: 2
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - area:infra
      - bloc-s
    open-pull-requests-limit: 1
