package com.widgetg7.core.datalayer

object GlucoseDataLayerContract {
    const val PATH_LATEST = "/glucose/latest"
    const val PATH_REFRESH_REQUEST = "/glucose/refresh/request"
    const val PATH_REFRESH_STATUS = "/glucose/refresh/status"
    const val PATH_WATCH_ACK = "/glucose/watch/ack"
    const val PATH_WATCH_STATUS_REQUEST = "/watch/status/request"
    const val PATH_WATCH_STATUS = "/watch/status"

    const val VALUE_MG_DL = "valueMgDl"
    const val TREND = "trend"
    const val DELTA_MG_DL = "deltaMgDl"
    const val TIMESTAMP_EPOCH_MS = "timestampEpochMs"
    const val STALE = "stale"
    const val SEQUENCE_ID = "sequenceId"
    const val TARGET_NODE_ID = "targetNodeId"
    const val SOURCE_PHONE_NODE_ID = "sourcePhoneNodeId"
    const val REFRESH_STATUS = "refreshStatus"
    const val REFRESH_MESSAGE = "refreshMessage"
    const val REFRESH_UPDATED_AT = "refreshUpdatedAt"
    const val REFRESH_IN_PROGRESS = "in_progress"
    const val REFRESH_COMPLETED = "completed"
    const val REFRESH_FAILED = "failed"
    const val WATCH_BATTERY_LEVEL = "watchBatteryLevel"
    const val WATCH_IS_CHARGING = "watchIsCharging"
    const val WATCH_LOW_POWER = "watchLowPower"
    const val WATCH_SYNC_LIMITED = "watchSyncLimited"
    const val WATCH_STATUS_MESSAGE = "watchStatusMessage"
    const val WATCH_STATUS_UPDATED_AT = "watchStatusUpdatedAt"
    const val WATCH_MANUFACTURER = "watchManufacturer"
    const val WATCH_MODEL = "watchModel"
    const val WATCH_DEVICE = "watchDevice"
    const val WATCH_APP_INSTALLED = "watchAppInstalled"
    const val WATCH_APP_VERSION_NAME = "watchAppVersionName"
    const val WATCH_APP_VERSION_CODE = "watchAppVersionCode"
    const val WATCH_SUPPORTS_TILE = "watchSupportsTile"
    const val WATCH_SUPPORTS_COMPLICATION = "watchSupportsComplication"
    const val WATCH_ACK_FAILURE_COUNT = "watchAckFailureCount"
    const val ACK_READING_TIMESTAMP_EPOCH_MS = "ackReadingTimestampEpochMs"
    const val ACK_SEQUENCE_ID = "ackSequenceId"
    const val ACK_RECEIVED_AT = "ackReceivedAt"
    const val PUSH_VERSION = "pushVersion"
}
