#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

SKIP_CHECKS=0
if [[ "${1:-}" == "--skip-checks" ]]; then
  SKIP_CHECKS=1
fi

latest_dir() {
  local base_dir="$1"
  if [[ ! -d "$base_dir" ]]; then
    return 1
  fi

  local latest
  latest="$(ls -1dt "$base_dir"/* 2>/dev/null | head -n 1 || true)"
  if [[ -z "$latest" ]]; then
    return 1
  fi

  echo "$latest"
}

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
OUT_DIR="build/e2e-closure/$TIMESTAMP"
LOGS_DIR="$OUT_DIR/logs"
mkdir -p "$LOGS_DIR"

EVIDENCE_DIR="${WIDGETG7_E2E_EVIDENCE_DIR:-}"
if [[ -z "$EVIDENCE_DIR" ]]; then
  EVIDENCE_DIR="$(latest_dir "build/e2e-evidence" || true)"
fi

if [[ -z "$EVIDENCE_DIR" || ! -d "$EVIDENCE_DIR" ]]; then
  echo "[widget-g7] No evidence pack found. Creating one."
  EVIDENCE_DIR="$(bash ./scripts/dev/prepare_e2e_evidence_pack.sh | tail -n 1)"
fi

DIAGNOSTICS_DIR="${WIDGETG7_DIAGNOSTICS_DIR:-}"
if [[ -z "$DIAGNOSTICS_DIR" ]]; then
  DIAGNOSTICS_DIR="$(latest_dir "build/diagnostics" || true)"
fi

run_check() {
  local check_name="$1"
  shift
  local log_file="$LOGS_DIR/${check_name}.log"

  if "$@" >"$log_file" 2>&1; then
    echo "PASS"
  else
    echo "FAIL"
  fi
}

VERIFY_CI_STATUS="SKIPPED"
VERIFY_RELEASE_STATUS="SKIPPED"
LEGAL_STATUS="SKIPPED"

if [[ "$SKIP_CHECKS" -eq 0 ]]; then
  echo "[widget-g7] Running closure checks"
  VERIFY_CI_STATUS="$(run_check "verify_ci" bash ./scripts/dev/verify_ci.sh)"
  VERIFY_RELEASE_STATUS="$(run_check "verify_release_artifacts" bash ./scripts/release/verify_release_artifacts.sh)"
  LEGAL_STATUS="$(run_check "check_legal_placeholders" bash ./scripts/release/check_legal_placeholders.sh)"
else
  echo "[widget-g7] Skip checks enabled (--skip-checks)"
fi

TECHNICAL_DECISION="NO-GO"
if [[ "$SKIP_CHECKS" -eq 1 ]]; then
  TECHNICAL_DECISION="PENDING (checks skipped)"
elif [[ "$VERIFY_CI_STATUS" == "PASS" && "$VERIFY_RELEASE_STATUS" == "PASS" && "$LEGAL_STATUS" == "PASS" ]]; then
  TECHNICAL_DECISION="GO"
fi

cat > "$OUT_DIR/SUMMARY.md" <<EOF
# E2E Closure Summary - $TIMESTAMP

Generated by: \`scripts/dev/finalize_e2e_closure_pack.sh\`

## Inputs

- evidence pack: \`$EVIDENCE_DIR\`
- diagnostics pack: \`${DIAGNOSTICS_DIR:-<not found>}\`
- skip checks: \`$SKIP_CHECKS\`

## Checks

| Check | Status | Log |
| --- | --- | --- |
| verify_ci | $VERIFY_CI_STATUS | \`$LOGS_DIR/verify_ci.log\` |
| verify_release_artifacts | $VERIFY_RELEASE_STATUS | \`$LOGS_DIR/verify_release_artifacts.log\` |
| check_legal_placeholders | $LEGAL_STATUS | \`$LOGS_DIR/check_legal_placeholders.log\` |

## Technical decision

\`$TECHNICAL_DECISION\`

## Next actions

1. Complete \`$EVIDENCE_DIR/notes/scenario_results_template.md\`.
2. Complete \`$EVIDENCE_DIR/notes/go_no_go_template.md\`.
3. Attach \`$OUT_DIR\` to the go/no-go decision record.
EOF

echo "[widget-g7] E2E closure pack ready: $OUT_DIR"
echo "$OUT_DIR"
