#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
OUT_DIR="build/e2e-evidence/$TIMESTAMP"
SCREENSHOTS_DIR="$OUT_DIR/screenshots"
LOGS_DIR="$OUT_DIR/logs"
NOTES_DIR="$OUT_DIR/notes"

mkdir -p "$SCREENSHOTS_DIR" "$LOGS_DIR" "$NOTES_DIR"

PHONE_SERIAL="${GFW_PHONE_SERIAL:-}"
WATCH_SERIAL="${GFW_WATCH_SERIAL:-}"

cat > "$OUT_DIR/README.md" <<EOF
# E2E Evidence Pack - $TIMESTAMP

Generated by: \`scripts/dev/prepare_e2e_evidence_pack.sh\`

## Expected content

- \`screenshots/\`: mobile app + watch tile/complication captures
- \`logs/\`: command outputs, WG7 log extracts, diagnostics exports
- \`notes/\`: scenario notes and go/no-go decision records

## Optional environment context

- phone serial: ${PHONE_SERIAL:-<not provided>}
- watch serial: ${WATCH_SERIAL:-<not provided>}
EOF

cat > "$NOTES_DIR/scenario_results_template.md" <<'EOF'
# Scenario Results Template

Date:
Operator:
Phone model + Android:
Watch model + Wear OS:
Phone serial:
Watch serial:

## Mandatory scenarios

| Scenario | Result (PASS/FAIL/BLOCKED) | Evidence path | Notes |
| --- | --- | --- | --- |
| Install debug phone + watch | TODO |  |  |
| First Dexcom sync visible on watch | TODO |  |  |
| Long idle sync (>= 8h) | TODO |  |  |
| Watch battery matrix (25/20/15/10, charging yes/no) | TODO |  |  |
| Multi-watch (switch primary node) | TODO |  |  |
| Full reinstall + tile/complication re-add | TODO |  |  |
| Release dry-run + legal gate | TODO |  |  |
EOF

cat > "$NOTES_DIR/go_no_go_template.md" <<'EOF'
# Go / No-Go Template

Date:
Owner:

## Inputs

- verify_ci: PASS/FAIL
- verify_release_artifacts: PASS/FAIL
- legal placeholders check: PASS/FAIL
- mandatory scenarios: PASS/FAIL

## Blocking issues

- None / list blockers

## Decision

- [ ] GO
- [ ] NO-GO

Rationale:
EOF

echo "[gfw] E2E evidence pack ready: $OUT_DIR"
echo "$OUT_DIR"
